# Generated by Django 4.1.2 on 2023-02-23 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sub_part', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='patient_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('gaurdian', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=10)),
                ('phone', models.TextField(max_length=10)),
                ('visit', models.TextField(max_length=10)),
            ],
        ),
    ]
