# Generated by Django 4.1.2 on 2023-02-23 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sub_part', '0002_patient_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='appointment_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date', models.CharField(max_length=20)),
                ('gender', models.CharField(max_length=10)),
                ('phone', models.TextField(max_length=10)),
                ('doctor', models.CharField(max_length=100)),
            ],
        ),
    ]
