# Generated by Django 4.1.2 on 2023-02-24 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sub_part', '0003_appointment_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='froappointment_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=30)),
                ('phone', models.TextField(max_length=10)),
                ('date', models.DateField(max_length=20)),
                ('department', models.CharField(max_length=20)),
                ('doctor', models.CharField(max_length=20)),
                ('message', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='register_table',
            name='email',
            field=models.EmailField(max_length=30),
        ),
    ]
