# Generated by Django 4.1.2 on 2023-02-25 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sub_part', '0005_contact_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='ipdpatient_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('patient', models.CharField(max_length=4)),
                ('gender', models.CharField(max_length=10)),
                ('charges', models.CharField(max_length=10000)),
                ('payment', models.CharField(max_length=10000)),
                ('due', models.CharField(max_length=10000)),
            ],
        ),
    ]
