# Generated by Django 4.1.2 on 2023-02-25 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sub_part', '0006_ipdpatient_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ipdpatient_table',
            name='charges',
            field=models.CharField(max_length=1000000),
        ),
        migrations.AlterField(
            model_name='ipdpatient_table',
            name='due',
            field=models.CharField(max_length=1000000),
        ),
        migrations.AlterField(
            model_name='ipdpatient_table',
            name='payment',
            field=models.CharField(max_length=1000000),
        ),
    ]
