# Generated by Django 4.1.2 on 2023-02-25 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sub_part', '0007_alter_ipdpatient_table_charges_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ipdpatient_table',
            old_name='patient',
            new_name='patient_id',
        ),
        migrations.RenameField(
            model_name='ipdpatient_table',
            old_name='name',
            new_name='patient_name',
        ),
    ]
