# Generated by Django 4.1.2 on 2023-02-25 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sub_part', '0008_rename_patient_ipdpatient_table_patient_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ipdpatient_table',
            old_name='charges',
            new_name='pay',
        ),
    ]
