# Generated by Django 4.1.2 on 2023-02-25 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sub_part', '0009_rename_charges_ipdpatient_table_pay'),
    ]

    operations = [
        migrations.AddField(
            model_name='register_table',
            name='profile_picture',
            field=models.ImageField(default=1, upload_to='documents'),
            preserve_default=False,
        ),
    ]
