# Generated by Django 4.1.2 on 2023-02-27 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sub_part', '0010_register_table_profile_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='froappointment_table',
            name='email',
        ),
    ]
