# Generated by Django 4.1.2 on 2023-03-16 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sub_part', '0011_remove_froappointment_table_email'),
    ]

    operations = [
        migrations.DeleteModel(
            name='appointment_table',
        ),
        migrations.DeleteModel(
            name='froappointment_table',
        ),
        migrations.DeleteModel(
            name='ipdpatient_table',
        ),
        migrations.DeleteModel(
            name='patient_table',
        ),
    ]
